require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
end

target 'App' do
  capacitor_pods

  # ✅ נוספו הפודים החסרים
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
